### ISSUE TITLE
TS Compiling TypeError: "Cannot set property 'oDataGet' of undefined"

### ISSUE THREAD

**Issue by johannesrue** [htammen/n-odata-server#6]
Hi!

I get an error after running the grunt-ts task and restarting the app:

>
C:\Users\jrueckert\workspace\Komplex-e\Komplex-e_head\js-loopback\node_modules\n-odata-server\lib\odata.js:23
    this.oDataGet = new ODataGetV2.ODataGet();
                  ^
TypeError: Cannot set property 'oDataGet' of undefined
    at _handleODataVersion2 (C:\Users\jrueckert\workspace\Komplex-e\Komplex-e_head\js-loopback\node_modules\n-odata-server\lib\odata.js:23:19)
    at module.exports (C:\Users\jrueckert\workspace\Komplex-e\Komplex-e_head\js-loopback\node_modules\n-odata-server\lib\odata.js:169:30)
    at C:\Users\jrueckert\workspace\Komplex-e\Komplex-e_head\js-loopback\node_modules\loopback-boot\lib\executor.js:425:5
    at Array.forEach (native)
    at setupComponents (C:\Users\jrueckert\workspace\Komplex-e\Komplex-e_head\js-loopback\node_modules\loopback-boot\lib\executor.js:418:27)
    at execute (C:\Users\jrueckert\workspace\Komplex-e\Komplex-e_head\js-loopback\node_modules\loopback-boot\lib\executor.js:35:3)
    at bootLoopBackApp (C:\Users\jrueckert\workspace\Komplex-e\Komplex-e_head\js-loopback\node_modules\loopback-boot\index.js:140:3)
    at Object.<anonymous> (C:\Users\jrueckert\workspace\Komplex-e\Komplex-e_head\js-loopback\server\server.js:21:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

I didn't change either the grunt config nor any of the files. After that i played around with the grunt-ts config and reinstalled the typings aswell, but no success so far. Any guess what might be wrong?

Thanks in advance!

Regards
Johannes

**Comment by epalmen** [comment]
Hi I experience the same problem. 
Is there a solution recommend. 
Regards Erik

**Comment by htammen** [comment]
Sorry for answering that late (had to earn some money during the last weeks). 
I just tested this issue but cannot reproduce it. What I did was:
* changed the file odata.ts
* ran grunt at command line
* checked if generated js file contained changes
* installed n-odata-server package into my sample project
* ran the sample project
* issued some OData requests
* verified that my changes were invoked

What tsc version do you use? Maybe there's a problem with some versions.
I used a rather old version 1.6.2
What OS are you using? I tested it with Mac OS X 10.11.4. Maybe there is an issue with tsc on other operating systems.

Regards Helmut

**Comment by htammen** [comment]
Could reproduce the problem and fixed it. 
Solution will be delivered with release 0.3.14. It's already available on github

Regards Helmut
