### ISSUE TITLE
Error on get http://server:port/odata/$metadata

### ISSUE THREAD

**Issue by renanwilliam** [htammen/n-odata-server#9]
When I try access myserver:3000/odata/$metadata it's returning this error:
[INFO] console - TypeError: commons.getPluralForModel is not a function
    at Metadata.<anonymous> (D:\Node\of-api\node_modules\n-odata-server\lib\base\metadata\metadata.js:55:34)
    at Array.forEach (native)
    at Metadata.buildMetadata (D:\Node\of-api\node_modules\n-odata-server\lib\base\metadata\metadata.js:18:28)
    at ODataGet._getMetadataDocument (D:\Node\of-api\node_modules\n-odata-server\lib\v2\get\odata_get.js:68:38)
    at ODataGet.handleGet (D:\Node\of-api\node_modules\n-odata-server\lib\v2\get\odata_get.js:31:38)
    at _handleGet (D:\Node\of-api\node_modules\n-odata-server\lib\odata.js:140:19)
    at D:\Node\of-api\node_modules\n-odata-server\lib\odata.js:35:32
    at Layer.handle [as handle_request] (D:\Node\of-api\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Node\of-api\node_modules\express\lib\router\index.js:312:13)
    at D:\Node\of-api\node_modules\express\lib\router\index.js:280:7

However when I access just /odata it's showing the correct document.

**Comment by htammen** [comment]
Fixed error when requesting $metadata file reported by renanwilliam on github.
Reason: since 0.3.10 there was a circular reference between odata_commons.ts and metadata.ts
